
GET http://localhost:4000/oauth2/authorize?client_id=yyit&response_type=code&redirect_uri=https://www.baidu.com&scope=message.read message.write

###

# 授权码交换令牌
POST http://localhost:4000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic eXlpdDp5eWl0

grant_type=authorization_code&redirect_uri=https%3A%2F%2Fwww.baidu.com&code=8hWs4F8he_nX1WSgMFdhT7YgaNp_PjF9_7JhD-GypG0-wlpe_JG12Kzp3D93xR0m02V5qcAdRSaFrZ6wCn86M1a0zr2oMWP_2Ue2ICM5cfQgOStsEeo4j7JajPBh3b09

###

# 令牌自省

POST http://localhost:4000/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic eXlpdDp5eWl0

token=eyJraWQiOiI3ZGQzZTQ2Mi03Yzg3LTRkNjAtYmZiNy0wZDg4ZjE0ZTZlM2UiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NjU3MTk0OTEsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6NDAwMCIsImV4cCI6MTY2NTcxOTc5MSwiaWF0IjoxNjY1NzE5NDkxfQ.U5wA-6FgomZrRx-9RNIT1ETvUCfQ5Ey57n5PUBBmlNX5aue8UkDO2skVEfJFqOa5ZNS_RoABvZCrUlJwMYZcDpQkD7C2PRDn6TAoAURObEuUJZwukT548qp3GoVcv0H5EC4ZU0qSzrX2slfCSTLFA07rb2h1vfr1JC5cwQhStTeeoRKHIm3cep2qFofHyJ-VmBzUOT2cFUe8NYfoQgCkWsrAikGigelKSr4BA_iqZpcWd3BoBwtFHakL4pFjOKmdBMmEVfYRDgqbwF_4vaaHldh6md9rV__5Ng8BHRuFYpj9kQVrPxPTnMcF5zxACQxiVCUMKkeOwp5an0NG1HrtQA

###

# 注销访问令牌

POST http://localhost:4000/oauth2/revoke
Content-Type: application/x-www-form-urlencoded
Authorization: Basic eXlpdDp5eWl0

token=eyJraWQiOiI3ZGQzZTQ2Mi03Yzg3LTRkNjAtYmZiNy0wZDg4ZjE0ZTZlM2UiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NjU3MTk0OTEsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6NDAwMCIsImV4cCI6MTY2NTcxOTc5MSwiaWF0IjoxNjY1NzE5NDkxfQ.U5wA-6FgomZrRx-9RNIT1ETvUCfQ5Ey57n5PUBBmlNX5aue8UkDO2skVEfJFqOa5ZNS_RoABvZCrUlJwMYZcDpQkD7C2PRDn6TAoAURObEuUJZwukT548qp3GoVcv0H5EC4ZU0qSzrX2slfCSTLFA07rb2h1vfr1JC5cwQhStTeeoRKHIm3cep2qFofHyJ-VmBzUOT2cFUe8NYfoQgCkWsrAikGigelKSr4BA_iqZpcWd3BoBwtFHakL4pFjOKmdBMmEVfYRDgqbwF_4vaaHldh6md9rV__5Ng8BHRuFYpj9kQVrPxPTnMcF5zxACQxiVCUMKkeOwp5an0NG1HrtQA

###

